#pragma once

#include "../vial_right/config.h"

#undef RGBLIGHT_LED_COUNT
#define RGBLIGHT_LED_COUNT 59

#undef RGBLED_SPLIT
#define RGBLED_SPLIT {30, 29}

#define WS2812_LED_COUNT RGBLIGHT_LED_COUNT

#define AUTO_MOUSE_TIME 500
#define KEYBALL_SCROLL_DIV_DEFAULT 6

#define SPLIT_TRANSACTION_IDS_USER \
  RIPPLE_EVENT_TRANSACTION, LIGHTING_FADE_TRANSACTION
