#pragma once

enum {
  RGBLIGHT_MODE_STATIC_LIGHT = 1,
  RGBLIGHT_MODE_BREATHING = 2,
  RGBLIGHT_MODE_BREATHING_end = 5,
  RGBLIGHT_MODE_RAINBOW_MOOD = 6,
  RGBLIGHT_MODE_RAINBOW_MOOD_end = 8,
  RGBLIGHT_MODE_RAINBOW_SWIRL = 9,
  RGBLIGHT_MODE_RAINBOW_SWIRL_end = 14,
  RGBLIGHT_MODE_SNAKE = 15,
  RGBLIGHT_MODE_SNAKE_end = 20,
  RGBLIGHT_MODE_KNIGHT = 21,
  RGBLIGHT_MODE_KNIGHT_end = 23,
  RGBLIGHT_MODE_CHRISTMAS = 24,
  RGBLIGHT_MODE_STATIC_GRADIENT = 25,
  RGBLIGHT_MODE_STATIC_GRADIENT_end = 34,
  RGBLIGHT_MODE_RGB_TEST = 35,
  RGBLIGHT_MODE_ALTERNATING = 36,
  RGBLIGHT_MODE_TWINKLE = 37,
  RGBLIGHT_MODE_TWINKLE_end = 42,
};
